VerizonAdPlatforms/VerizonVideoPartnerSDK-controls-ios

- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/DefaultControlsViewController.swift
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-32)
> Fixed duration label visibility at iOS content player controls

- PlayerControls/resources/DefaultControlsViewController.xib
> PiP and Settings button swap

- Demo/Demo/AppDelegate.swift
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/sources/DefaultControlsViewController.swift
In current interface either live or duration can be
displayed.
This is modelled by `Duration` enum in `Props`
> Add support of live button.

- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/ContentControlsUIProps.swift
Seekbar bottom constraint now depends on visibility of:
So if all of this is hidden - we put seekbar to bottom - otherwise it stays in initial position.
> Seekbar constraint logic fix

- PlayerControls/resources/DefaultControlsViewController.xib
Request from *aol.com* team - in general good concept.
> Live button have to be always visible and should not be hidden when all controls is hidden

- Demo/Demo/AppDelegate.swift
- PlayerControls/resources/DefaultControlsViewController.xib
> Reverted changes which were made to support iPhone X

- PlayerControls/resources/DefaultControlsViewController.xib
Before: | After
--------|------
> Fixed controls shadow curtain bottom constraint

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/PlayerControls.xcodeproj/xcshareddata/xcschemes/PlayerControls.xcscheme
- PlayerControls/tests/ControlsVisibilityControllerTests.swift
- PlayerControls/tests/FormatterTests.swift
- PlayerControls/tests/SideBarViewTests.swift
No reason for this simple tests have quick & nimble.
> Dropped quick & nimble + switch to XCTest

- .travis.yml
- fastlane/Fastfile
Implemented Travis Continuous Integration that will build our project and will run its tests.
> Implemented Travis CI 

- PlayerControls/sources/Command.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
Proposed to use Progress phantom type instead Double
> Add Progress phantom type

- Demo/Demo/AppDelegate.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/Codable.swift
- PlayerControls/sources/Color.swift
- PlayerControls/sources/Command.swift
- PlayerControls/sources/ContentControlsUIProps+Init.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- SnapshotTests/DefaulController/CaseWithThumbnail.swift
In this pull request all properties (`AdVideoControls.Props`, `ContentControlsViewController.Props`, `SideBarView.ButtonProps`) are `Codable`. 
Still in progress...
> Implemented Codable

- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/DefaultControlsViewController.swift
Add accessibility to default controls in storyboard
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-516)
> Add accessibility to default controls xib

- PlayerControls/resources/AdVideoControls.xib
Add accessibility to ad controls in storyboard
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-516)
> Add accessibility to ad controls xib

- PlayerControls/sources/SideBarView.swift
- SnapshotTests/DefaulController/CaseWithAirplayActive.swift
- SnapshotTests/DefaulController/CaseWithAllControls.swift
Need to add API for sidebar buttons accessibility (label, hint, traits)
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-623)
> Add API for sidebar buttons accessibility

- PlayerControls/resources/AdVideoControls.xib
- PlayerControls/sources/ContentControlsUIProps.swift
1. Ad seeker accessibility traits
2. Content seeker accessibility label
> Fix seeker accessibility

- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/Codable.swift
- SnapshotTests/AdVideoController/CaseWithAdLoading.swift
- SnapshotTests/AdVideoController/CaseWithAirPlayActive.swift
Supporting detection of SFSafariViewController close event to properly manage clickthrough.
> Ad click support

- PlayerControls/sources/DefaultControlsViewController.swift
@RomanTysiachnik dropped my code while merging animations code.
> Hotfix for cuepoints

- PlayerControls/sources/DefaultControlsViewController.swift
Added missing animation for shadow view.
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-675)
> Fixed appearance for shadow view

- PlayerControls/resources/DefaultControlsViewController.xib
Fixed incorrect value for sideBar's invisible constraint to fully hide sideBar on every device.
> Fixed constraint for sideBar

- PlayerControls/sources/DefaultControlsViewController.swift
Removed animation from layer when play, pause or replay button replace each other.
> Fix for Play Pause and Replay buttons

- Demo/Demo/AppDelegate.swift
- PlayerControls/sources/ContentControlsUIProps+Init.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
Moved animationsEnabled value in a correct place.
> Moved animationsEnabled from Player to Controls

- PlayerControls/sources/SeekerControlView.swift
On iPhone 5S cue points rendering takes too much CPU resources. Optimized view creation/deletion.
> Optimizing cue points rendering

- PlayerControls/sources/DefaultControlsViewController.swift
I've added a new flag - controlsAnimationEnabled that now will depend on:
- `uiProps` value;
- `State` struct with next values:
- `hasAppeared` - if the view has appeared ;
- `isTransitioning` - if transition in proccess.
- `controlsAnimationPossible` -  affects the adding of animations to controls layers. It will be true, if the view has appeared and if view isn't transitioning.
**Broken:**
**Fixed:**
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-700)
> Removed controls animation during transitions

- PlayerControls/sources/DefaultControlsViewController.swift
Note: it looks like a lot of changes have been added but in fact, it is not. For better understanding, you should open the entire file and review from there. All of the changes were done in `viewWillLayoutSubviews `.
All of the changes were done in `DefaultControlsViewController`:
What fixes bring these changes:
- Animations are added to each view only when they need to animate;
- Now each component decides if it needs an animation to be added;
- Fixed incorrect layout when device orientation is changed, including orientation changes after the animation is started;
- Possibility to compare current UI and next UI;
WIP:
> Refactored DefaultControlsViewController to ensure correct animations

- Demo/Demo/AppDelegate.swift
Added timer for the demo that changes progress every 0.2 sec imitating playback.
@aol-public/mobile-sdk-team ready for review.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-796)
> Added timer for Demo that changes props every 0.2 sec

- PlayerControls/sources/Defaultable.swift
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-1363)
> Added Defaultable for Seekbar colors

- podspec/PlayerControls.podspec
- Moved `.podspec` file inside `podspec` folder.
- Added platform, submodules, and frameworks.
- Fixed mistakes in `description` and `authors`.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-1573)
> Fixed podspec issues

- PlayerControls/PlayerControls.xcodeproj/xcshareddata/xcschemes/PlayerControls.xcscheme
- PlayerControls/sources/Codable_PlayerControls.generated.swift
- PlayerControls/sources/EnumPrism_PlayerControls.generated.swift
> Xcode warning fix

- Demo/Demo.xcodeproj/project.pbxproj
- Demo/Demo/AppDelegate.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/AirPlayView.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- PlayerControls/sources/SeekerControlView.swift
- PlayerControls/sources/SideBarView.swift
- PlayerControls/sources/Timer.swift
- SnapshotTests/DefaulController/CaseWithAirplayActive.swift
- SnapshotTests/DefaulController/CaseWithAllControls.swift
- SnapshotTests/SnapshotTests.xcodeproj/project.pbxproj
Most of the changes are connected with `UIKit` updates and some fixes in snapshot tests.
> PlayerControls Swift 4.2 migration

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/resources/AdVideoControls.xib
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- PlayerControls/sources/Utils.swift
- PlayerControls/sources/loading image/LoadingImageView.swift
Now the `LoadingImageView` will replace the common `UIImageView` for loading indication. It is also marked as public to make it reusable in our SDK.
@OathAdPlatforms/mobile-sdk-developers: Please review.
> Added loading image view to make it reusable

- .github/PULL_REQUEST_TEMPLATE.md
- .gitmodules
- .travis.yml
- PlayerControls/resources/SeekerControlPlayground.xib
- PlayerControls/sources/Codable_PlayerControls.generated.swift
- PlayerControls/sources/ControlsVisibilityController.swift
- PlayerControls/sources/EnumPrism_PlayerControls.generated.swift
- README.md
- fastlane/Fastfile
- podspec/PlayerControls.podspec
> Repo links update + release 1.28

- podspec/PlayerControls.podspec
[JIRA Ticket](https://jira.ouroath.com/browse/OMSDK-2258)
> Bump pod spec to 1.29

- Demo/Demo/AdControls.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/AirPlayActiveView.swift
- PlayerControls/sources/BundleHelper.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- PlayerControls/sources/Utils.swift
- podspec/PlayerControls.podspec
Supplying resource bundle instead of `resources` which sometimes work and sometimes not.
[JIRA Ticket](https://jira.ouroath.com/browse/OMSDK-2259)
> 1.30 release with resource fix

- podspec/PlayerControls.podspec
- I've removed `traits` value from `Accessibility` struct and added a public init for it, so the new version is 2.0
> Player Controls release 2.0

- PlayerControls/sources/AdVideoControls.swift
> Added dynamic accessibility id for ad skip button

- PlayerControls/sources/Codable_PlayerControls.generated.swift
- PlayerControls/sources/EnumPrism_PlayerControls.generated.swift
> Updated build scripts

- podspec/PlayerControls.podspec
> Bump pod spec to 2.0.1

- PlayerControls/resources/AdVideoControls.xib
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/AdVideoControls.swift
> Sync accessibility between platforms

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
[JIRA Ticket](https://jira.ouroath.com/browse/VSDK-4659)
> Switched to manual code signing

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/PlayerControls.xcodeproj/xcshareddata/xcschemes/PlayerControls.xcscheme
- PlayerControls/sources/EnumPrism_PlayerControls.generated.swift
> Updated build scripts with updated generation and added Xcode 10.2 changes

- PlayerControls/resources/DefaultControlsViewController.xib
> Moved side bar in controls view hierarchy

- CHANGELOG.md
- PlayerControls.podspec
> Player Controls 2.0.3 release
