VerizonAdPlatforms/VerizonVideoPartnerSDK-controls-ios

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- PlayerControls/sources/Defaultable.swift
- PlayerControls/sources/stencil.sh
```
playerVC.customizeContentControlsProps = { props in
guard case .player(let controls) = props else { return props }
guard case .playable(let content) = controls.item else { return props }
var newContent = content
newContent.live.dotColor = .red
return .player(.init {
$0.playlist = controls.playlist
$0.item = .playable(newContent)
})
}
```
> Supporting live dot coloring (by default tint is used)

- PlayerControls/resources/SettingsViewController.xib
- PlayerControls/sources/SettingsViewController+TableView.swift
- PlayerControls/sources/SettingsViewController.swift
> Height of settings tableview now calculated dynamically - depending on content size 

- PlayerControls/resources/DefaultControlsViewController.xib
On small players error label was squashed (aol.com report):
> Error label layout update

- PlayerControls/sources/DefaultControlsViewController.swift
Proposed to check is `liveDotLabel.textColor` not nill and use this value.
**Reason**: If set `controls.live.dotColor` on init when player is updated it will become nill because `ContentControlsViewController+Binding` contains 
```
return Controls.Live {
$0.isHidden = !item.content.time.isLive
$0.dotColor = nil
}
```
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-447)
> Fix live dot color changing

- Demo/Demo/AppDelegate.swift
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/templates/EnumPrism.stencil
Implemented  `public protocol GeneratePrism {}` for enums which needs to be extended by EnumPrism. In EnumPrism.stencil I've deleted setters and changed `for enum in types.enums where enum.cases.all.count > 0 and not enum.accessLevel == 'private'` to `for enum in types.implementing.GeneratePrism|enum`. 
Now, all enums marked `GeneratePrism` are extending by EnumPrism
> Modified EnumPrisma.stencil for extending only necessary enums

- Demo/Demo/AppDelegate.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/Command.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/sources/ControlsVisibilityController.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- PlayerControls/sources/SeekerControlView.swift
- PlayerControls/sources/SettingsViewController+TableView.swift
- PlayerControls/sources/SettingsViewController.swift
- PlayerControls/sources/SideBarView.swift
- PlayerControls/sources/Timer.swift
- PlayerControls/sources/Utils.swift
This new type was added to replace our old implementation of closures usage. 
CommandWith is a generic struct with type T, where T is a closure that you send.
To present your variable as a Command, you should specify its type. By default, Command has an empty closure that doesn't receives and doesn't returns anything:`(Void) -> (Void)`. To use any other type as a received one, you should specify it as `CommandWith<Type>`.
> Added Command as a replacement for Actions

- PlayerControls/tests/ControlsVisibilityControllerTests.swift
A hot fix for our tests of controls visibility. After adding a `Command` to a project, it was now added to our `Recorder` instead of closures that have to return `Command` to match requested type. Those closures, that are used only in `Recorder` were not changed.
Also, in `ControlsVisibilityControllerTests`, all Commands perform actions that they contain and now all our tests pass.
> Added Command in controls visibility controller tests

- PlayerControls/templates/EnumPrism.stencil
Sourcery of version 0.10.0 has broken our Stencil prism. They've removed their filters, including `upperFirst` and now they are using filters from StencilSwiftKit. This change caused an error while the stencil file was compiled, because it wasn't able to find the `upperFirst` filter. 
Now this filter is called `capitalize` and it is added to our enum prism.
> Fixed EnumPrism.stencil crash after Sourcery update

- .gitignore
- PlayerControls/Cartfile.private
- PlayerControls/Cartfile.resolved
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
Removed unnecessary files and records of Carthage, that have been located in PlayerControls. We used to have a Carthage to add **Quick** and **Nimble** frameworks in our project. As soon as it is gone, Cartfiles and a framework search path should be removed. Especially the last one, that caused a warning.
> Removed all Carthage references in PlayerControls

- Demo/Demo/AppDelegate.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/ContentControlsUIProps+Init.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/sources/Defaultable.swift
- PlayerControls/sources/SettingsViewController.swift
- PlayerControls/sources/SideBarView.swift
In this PR added initializers  for ContentControlsViewController Props as an extension in a new file 
Refactored ContentControlsViewController and it doesn't contain nesting anymore. Instead of `Props.Player.Item.Controls`  we got `Props.Controls`. So, we don't have to describe all path to the type we want to create.
As a result we have a new way to initialise Props:
<details>
<summary>Click to see original</summary>
<pre>
func props() -> Props {
return Props.player(Props.Player{ player in
player.playlist = nil
player.item = .playable(Props.Controls { controls in
controls.title = "Some title very very very very very very very very very long"
controls.live.isHidden = true
controls.seekbar = .init()
controls.playbackAction = .pause(.nop)
controls.camera = Props.Camera()
controls.settings = …
> Initializers  for ContentControlsViewController Props

- PlayerControls/sources/ContentControlsUIProps+Init.swift
In this PR added initializers  for ContentControlsViewController Props as an extension in a new file 
Refactored ContentControlsViewController and it doesn't contain nesting anymore. Instead of `Props.Player.Item.Controls`  we got `Props.Controls`. So, we don't have to describe all path to the type we want to create.
As a result we have a new way to initialise Props:
<details>
<summary>Click to see original</summary>
<pre>
func props() -> Props {
return Props.player(Props.Player{ player in
player.playlist = nil
player.item = .playable(Props.Controls { controls in
controls.title = "Some title very very very very very very very very very long"
controls.live.isHidden = true
controls.seekbar = .init()
controls.playbackAction = .pause(.nop)
controls.camera = Props.Camera()
controls.settings = …
> Init for props

- PlayerControls/sources/AirPlayView.swift
The test button was added to exclude situations when this view will be rendered, but the MPVolumeView will not, because of the absence of wireless routes. Now, when the project will be launched on the simulator, it will render only a new button for testing, that looks exactly like the original.
> Modified AirPlayView to make AirPlay testable on iOS Simulator

- PlayerControls/sources/SeekerControlView.swift
If tint color has not been changed, seeker bar time color remains black.
Actual: Seeker bar time color is black
Expected: Seeker bar time color as tint
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-545)
> Fix default seeker bar time color

- PlayerControls/sources/ControlsVisibilityController.swift
If disable view hiding with `controlsViewHidden` app gets crash on `ControlsPresentationController.hiddenPaused()`. It can be fixed with ignoring `resetTimer` message in `ControlsPresentationController.hiddenPaused()` or redesign `ContentControlsViewController.Props.player` with rewriting logic in `DefaultControlsViewController`.
@AndriiMoskvin @AlexeyDemedetskiy
> Ignore resetTimer on hiddenPaused

- PlayerControls/sources/ContentControlsUIProps.swift
Removed checks for next items to avoid their hiding on a timer or tap:
- Error label
- Airplay active label
- Thumbnail image view
- Retry button
[Jira Issue](https://jira.ouroath.com/browse/OMSDK-678)
> Removed unnecessary controlsHidden checks

- PlayerControls/sources/ContentControlsUIProps.swift
The Replay's visibility now depends only on uiProps state, so it wouldn't disappear on tap anymore.
> Removed controlsHidden check for Replay button

- PlayerControls/resources/AdVideoControls.xib
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/DefaultControlsViewController.swift
To get the `Home Indicator` hiding behavior from `DefaultViewController`, that will hide it right after controls, you should make `DefaultViewController` responsible for this hiding, using method `childViewControllerForHomeIndicatorAutoHidden` in the `rootViewController`.
@aol-public/mobile-sdk-team  Ready to review.
[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-722)
> Added iPhone X Support

- .travis.yml
- manage-diffs.sh
Fixed an issue that errored pull-request build on Travis because of environmental variables that are not available on forks. Now it will be launched only if PR was made from **aol-public** branch
Also, the deployment configuration and the diff images management are now located in diffs-deploy.sh file.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-770)
> Hotfix for travis.yml and diffs deploy

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- PlayerControls/sources/AdVideoControls.swift
- PlayerControls/sources/Autogeneratable.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/templates/Codable.stencil
To reduce writing repetitive code was implementing autogenerated code for Codable by using sourcery. `protocol AutoCodable` was implemented to mark enums which have to be extended  by `protocol Codable` (same why we have in `Prism` for generating enumPrism)
Codable.stensil have been added to replace Codable.swift and make project looks cleaner.
> Sourcery for codable

- PlayerControls/resources/DefaultControlsViewController.xib
I've added the `safe area` for the `Live indicator` for its `top anchor`.
Here's how it will look like:
> Added safe area for LIVE indicator 

- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/DefaultControlsViewController.swift
- `Sidebar view`
- `Seeker view`
- `Airplay view` and `Pip button`
- Removed size classes dependencies for all views;
- Added necessary checks in `setupBottomItemsConstraints` to prevent turning on constraint when it is not possible;
- Fixed constraint switch for the sidebar in `renderSideBar` method;
- Minor fixes in code.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-851)
> Fixed constraint warnings

- PlayerControls/sources/ContentControlsUIProps.swift
We've had a discussion about that and decided that if autoplay is turned off, play button should always be visible on the screen. We show thumbnails only when autoplay is off, so I've decided to extend visibility logic for the play button, that is now also based on the thumbnail visibility.
| Before        | After           |
| ------------- |:-------------:|
| ![autoplay-before](https://user-images.githubusercontent.com/31652265/37962940-6f093558-31c5-11e8-89b3-6e5ed2e99c64.gif)  | ![autoplay-after](https://user-images.githubusercontent.com/31652265/37962945-741ee790-31c5-11e8-9e30-da6b7a4f0c20.gif)
|
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-844)
> Play button is now always visible with thumbnail

- PlayerControls/sources/DefaultControlsViewController.swift
To improve UX, I've added a new state `isSeekingInProgress`. So now, when you start seeking, buttons disappear immediately, without fade.
| Before        | After           |
| ------------- |:-------------:|
| ![seeking-before](https://user-images.githubusercontent.com/31652265/37962744-ba2ea0f0-31c4-11e8-870a-c48dcc48f8b3.gif)      | ![seeking-after](https://user-images.githubusercontent.com/31652265/37962745-ba512d28-31c4-11e8-9553-7deaa8638bc0.gif) |
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-845)
> Turned off animations when seeking started

- PlayerControls/sources/DefaultControlsViewController.swift
I've added that logic to ensure that sidebar will appear exactly when expected even after transition. 
After some changes in xib, this logic is not needed anymore. In fact, it now causes a bug on an iPad, so I've removed it at all.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-869)
> Removed unnecessary logic for sidebar's constraint

- Demo/Demo/AppDelegate.swift
- PlayerControls/resources/DefaultControlsViewController.xib
- PlayerControls/sources/ContentControlsUIProps+Init.swift
- PlayerControls/sources/ContentControlsUIProps.swift
- PlayerControls/sources/ContentControlsViewController.swift
- PlayerControls/sources/DefaultControlsViewController.swift
- Implemented double tap gesture recognizer;
- Added gesture recognizer delegate that won't send double taps through buttons;
- Added contentFullScreen property;
- One tap gesture recognizer now works only if double tap fails;
- Updated demo with background color switch to demonstrate how two gesture recognizers work;
- Naming - looking forward for your propositions about naming;
- Controls hide/show on tap delay, because tap gesture now will be triggered after double tap fails.
```swift
onEmptySpaceGestureRecognizer.require(toFail: contentFullScreenGestureRecognizer)
```
There's now a small delay before `onEmptySpaceGestureRecognizer` will be triggered. It is typical behavior for default AVPlayerViewController, but we should increase `animationDuration` for better UX. …
> Added double tap recognizer to toggle content video gravity

- PlayerControls/resources/DefaultControlsViewController.xib
Fixed issue with `compass direction view` on iOS 10.3.3 and lower.
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-1091)
> Removed unnecessary constraints from 360 direction view

- PlayerControls.podspec
- Sources now get all swift files from `PlayerControls` folder to be able to reach `Autogeneretable.swift` file
- Excluded `tests` folder
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-1573)
> Minor fixes in podspec with source files

- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- Minor fix in `xcodeproj` file to remove olds references 
| <img width="272" alt="screen shot 2018-09-10 at 2 35 07 pm" src="https://user-images.githubusercontent.com/31652265/45740759-a50d4e00-bbfe-11e8-83c0-9d6e4f10314d.png"> | 
| - | - | 
[JIRA Issue](https://jira.ouroath.com/browse/OMSDK-1605)
> Removed incorrect paths in project

- Demo/Demo.xcodeproj/project.pbxproj
- Demo/Demo/AdControls.swift
- Demo/Demo/AppDelegate.swift
- Demo/Demo/ContentControls.swift
- Demo/Demo/Controls.swift
- PlayerControls/PlayerControls.xcodeproj/project.pbxproj
- SnapshotTests/SnapshotTests.xcodeproj/project.pbxproj
- It is now easier to select Controls ViewController for ad or content from AppDelegate
> Added Controls enum to remove all vc configuration from App delegate

- PlayerControls/sources/SideBarView.swift
- Dropped `traits` property from `Accessibility` struct. Now the `acessibilityTraits` property will always be `button`. 
- Used constructor instead of `static var` to fix an issue on Swift 4.0.
- Added `public init` for `Accessibility` struct because before it was internal and customers were not able to set an accessibility for their buttons
> Fixed AccessibilityTraits that caused crash on Swift 4.0

- PlayerControls/sources/ContentControlsUIProps.swift
> Replay button now will be shown only for the last video in playlist
